import { StyleSheet, type ViewStyle } from "react-native"
import { DEFAULT_FOLDER_PANE_WIDTH, DIVIDER_WIDTH, MAX_FOLDER_PANE_WIDTH, MIN_FOLDER_PANE_WIDTH, MIN_MESSAGE_PANE_WIDTH } from "./layoutConstants"

export const styles = StyleSheet.create({
  clickable: { cursor: "pointer" } as unknown as ViewStyle,
  shell: { flex: 1, backgroundColor: "#f2f4f8" },
  toolbar: { minHeight: 58, backgroundColor: "#f8fbff", borderBottomColor: "#c8d3df", borderBottomWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 14 },
  toolbarMobile: { alignItems: "stretch", flexDirection: "column", gap: 6, minHeight: 0, paddingHorizontal: 10, paddingVertical: 8 },
  toolbarTitleRow: { alignItems: "center", flexDirection: "row", gap: 8, minWidth: 0 },
  toolbarTitle: { color: "#1d2d44", fontSize: 19, fontWeight: "800" },
  toolbarTitleMobile: { flex: 1, fontSize: 17, minWidth: 0 },
  toolbarActions: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  toolbarActionsScroller: { width: "100%" },
  toolbarActionsMobile: { flexDirection: "row", flexWrap: "nowrap", gap: 8, justifyContent: "flex-start", paddingRight: 10 },
  notice: { backgroundColor: "#e7f3ff", borderBottomColor: "#b6d7f4", borderBottomWidth: 1, color: "#174d7c", paddingHorizontal: 14, paddingVertical: 8 },
  vaultUnlock: { alignItems: "center", backgroundColor: "#fff7ed", borderBottomColor: "#fed7aa", borderBottomWidth: 1, flexDirection: "row", gap: 10, paddingHorizontal: 14, paddingVertical: 8 },
  vaultUnlockText: { color: "#7c2d12", fontWeight: "800" },
  vaultUnlockInput: { backgroundColor: "#ffffff", borderColor: "#fdba74", borderWidth: 1, color: "#111827", minWidth: 220, paddingHorizontal: 10, paddingVertical: 8 },
  vaultUnlockError: { color: "#9f1239", fontWeight: "800" },
  workspace: { flex: 1, flexDirection: "row", minHeight: 0 },
  folderPaneFallback: { backgroundColor: "#eef3f9", flexBasis: DEFAULT_FOLDER_PANE_WIDTH, flexGrow: 0, flexShrink: 0, maxWidth: MAX_FOLDER_PANE_WIDTH, minWidth: MIN_FOLDER_PANE_WIDTH, overflow: "hidden", width: DEFAULT_FOLDER_PANE_WIDTH },
  folderPaneScroll: { flex: 1, minWidth: 0 },
  folderDrawerBackdrop: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0, zIndex: 900 },
  folderDrawerScrim: { backgroundColor: "rgba(15, 23, 42, 0.34)", bottom: 0, left: 0, position: "absolute", right: 0, top: 0 } as unknown as ViewStyle,
  folderDrawerPanel: { backgroundColor: "#eef3f9", borderRightColor: "#c8d3df", borderRightWidth: 1, bottom: 0, left: 0, maxWidth: 360, position: "absolute", top: 0, width: "86%" } as unknown as ViewStyle,
  folderDrawerHeader: { alignItems: "center", borderBottomColor: "#c8d3df", borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 12, paddingVertical: 10 },
  dragDivider: { backgroundColor: "#c8d3df", flexShrink: 0, width: DIVIDER_WIDTH },
  folderPaneContent: { padding: 8, gap: 3 },
  paneHeader: { color: "#344963", fontSize: 13, fontWeight: "800", marginBottom: 8, textTransform: "uppercase" },
  sectionHeader: { color: "#64748b", fontSize: 12, fontWeight: "800", marginTop: 16, marginBottom: 6, textTransform: "uppercase" },
  folderButton: { alignItems: "center", flexDirection: "row", gap: 6, justifyContent: "space-between", paddingHorizontal: 6, paddingVertical: 5 },
  folderButtonActive: { backgroundColor: "#cfe5ff" },
  folderButtonDropTarget: { backgroundColor: "#e0f2fe", borderColor: "#38bdf8", borderWidth: 1 },
  folderLabelGroup: { flex: 1, minWidth: 0 },
  folderButtonText: { color: "#24364e", flex: 1, fontSize: 14, fontWeight: "600", minWidth: 0 },
  folderButtonTextActive: { color: "#074a91" },
  folderBadgeText: { color: "#64748b", fontSize: 10, fontWeight: "800", marginTop: 2, textTransform: "uppercase" },
  folderCount: { color: "#64748b", flexShrink: 0, fontWeight: "800" },
  accountTree: { marginTop: 8 },
  accountTreeHeader: { paddingHorizontal: 8, paddingVertical: 7 },
  accountTreeName: { color: "#1f2f45", fontWeight: "800" },
  accountTreeServer: { color: "#64748b", fontSize: 12, marginTop: 2 },
  accountTreeStatus: { color: "#64748b", fontSize: 11, marginTop: 3 },
  accountTreeError: { color: "#9f1239", fontSize: 11, fontWeight: "800", marginTop: 3 },
  mailWorkspace: { flex: 1, flexDirection: "row", minWidth: 0 },
  mailWorkspaceMobile: { flex: 1, flexDirection: "column", minWidth: 0 },
  threadPaneFallback: { backgroundColor: "#ffffff", flexBasis: "50%", flexGrow: 0, flexShrink: 0, minWidth: MIN_MESSAGE_PANE_WIDTH, overflow: "hidden", width: "50%" },
  threadPaneMobile: { backgroundColor: "#ffffff", flex: 1, minWidth: 0 },
  threadHeader: { borderBottomColor: "#d5dde7", borderBottomWidth: 1, padding: 14 },
  threadTitle: { color: "#172033", fontSize: 20, fontWeight: "800" },
  threadSubtle: { color: "#64748b", marginTop: 5 },
  statusInline: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 5 },
  searchRow: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 12 },
  searchRowMobile: { alignItems: "stretch", flexWrap: "wrap" },
  searchInput: { backgroundColor: "#ffffff", borderColor: "#b7c5d4", borderWidth: 1, color: "#111827", flex: 1, fontSize: 14, minWidth: 0, paddingHorizontal: 10, paddingVertical: 8 },
  messageListShell: { flex: 1, minHeight: 0, position: "relative" },
  messageList: { flex: 1, backgroundColor: "#ffffff" },
  messageRow: { borderBottomColor: "#e2e8f0", borderBottomWidth: 1, gap: 4, paddingHorizontal: 12, paddingVertical: 10 },
  messageRowFlagged: { backgroundColor: "#fffbeb" },
  messageRowDone: { backgroundColor: "#f0fdf4" },
  messageRowActive: { backgroundColor: "#dbeafe" },
  messageRowFlaggedActive: { backgroundColor: "#fef3c7" },
  messageRowDoneActive: { backgroundColor: "#dcfce7" },
  messageRowTop: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" },
  messageSenderGroup: { alignItems: "center", flex: 1, flexDirection: "row", gap: 7, minWidth: 0 },
  unreadMarker: { backgroundColor: "#0b63ce", height: 7, width: 7 },
  messageSender: { color: "#172033", flex: 1, fontWeight: "800", minWidth: 0 },
  messageSenderRead: { color: "#334155", fontWeight: "600" },
  messageRowActions: { alignItems: "center", flexDirection: "row", flexShrink: 0, gap: 6 },
  messageDate: { color: "#64748b", flexShrink: 0, fontSize: 11 },
  flagButton: { alignItems: "center", height: 24, justifyContent: "center", width: 24 },
  messageSubject: { color: "#24364e", fontWeight: "800" },
  messageSubjectRead: { color: "#475569", fontWeight: "600" },
  messageMetaText: { color: "#64748b", fontSize: 12 },
  messagePreviewText: { color: "#64748b", lineHeight: 18 },
  attachmentText: { color: "#0b4f9c", fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  attachmentList: { backgroundColor: "#f8fbff", borderColor: "#d8e2ee", borderWidth: 1, gap: 8, marginTop: 10, padding: 8 },
  attachmentListHeader: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" },
  attachmentListTitle: { color: "#24364e", fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  attachmentGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  attachmentItem: { alignItems: "center", backgroundColor: "#ffffff", borderColor: "#cbd7e3", borderWidth: 1, flexBasis: 210, flexDirection: "row", flexGrow: 1, gap: 8, justifyContent: "space-between", minWidth: 0, paddingHorizontal: 7, paddingVertical: 5 },
  attachmentFileText: { flex: 1, minWidth: 0 },
  attachmentName: { color: "#172033", fontSize: 13, fontWeight: "800" },
  attachmentMeta: { color: "#64748b", fontSize: 11, marginTop: 2 },
  attachmentActions: { alignItems: "center", flexDirection: "row", flexShrink: 0, gap: 5 },
  attachmentLoadingText: { color: "#64748b", fontSize: 11, fontWeight: "800" },
  contextMenuLayer: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0, zIndex: 1200 },
  contextMenuLayerWeb: { position: "fixed" } as unknown as ViewStyle,
  contextMenuBackdrop: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0 } as unknown as ViewStyle,
  contextMenu: { backgroundColor: "#ffffff", borderColor: "#94a3b8", borderWidth: 1, minWidth: 210, paddingVertical: 4, position: "absolute", shadowColor: "#0f172a", shadowOpacity: 0.18, shadowRadius: 12, zIndex: 1201 } as unknown as ViewStyle,
  contextMenuItem: { alignItems: "center", flexDirection: "row", gap: 9, paddingHorizontal: 12, paddingVertical: 9 },
  contextMenuText: { color: "#172033", fontSize: 13, fontWeight: "800" },
  contextMenuTextDestructive: { color: "#b91c1c" },
  loadMoreArea: { alignItems: "center", borderTopColor: "#e2e8f0", borderTopWidth: 1, paddingHorizontal: 12, paddingVertical: 14 },
  emptyThreads: { padding: 22 },
  emptyTitle: { color: "#1f2f45", fontSize: 18, fontWeight: "800" },
  emptyCopy: { color: "#64748b", lineHeight: 22, marginTop: 8 },
  readerPane: { backgroundColor: "#fbfcfe", flex: 1, minWidth: MIN_MESSAGE_PANE_WIDTH, padding: 28 },
  readerPaneMobile: { minWidth: 0, overflow: "hidden", padding: 14 },
  readerContent: { paddingBottom: 40 },
  readerTitleRow: { alignItems: "flex-start", flexDirection: "row", gap: 10, justifyContent: "space-between" },
  readerTitleRowMobile: { flexWrap: "nowrap" },
  readerTitle: { color: "#172033", flex: 1, fontSize: 24, fontWeight: "800", minWidth: 0 },
  readerTitleMobile: { flexBasis: 0, overflowWrap: "anywhere", wordBreak: "break-word" } as unknown as ViewStyle,
  readerMeta: { color: "#64748b", marginTop: 8 },
  readerBody: { color: "#172033", fontSize: 15, lineHeight: 23, marginTop: 24, maxWidth: "100%", overflowX: "auto", whiteSpace: "pre-wrap" } as unknown as ViewStyle,
  readerLoading: { alignItems: "flex-start", marginTop: 24 },
  htmlPreviewBlock: { marginTop: 24, maxWidth: "100%", overflowX: "auto", overflowY: "visible" } as unknown as ViewStyle,
  inlineContentNotice: { backgroundColor: "#eff6ff", borderColor: "#bfdbfe", borderWidth: 1, gap: 10, marginBottom: 12, padding: 12 },
  inlineContentText: { color: "#1e3a8a", fontWeight: "800", lineHeight: 20 },
  remoteContentNotice: { backgroundColor: "#fff7ed", borderColor: "#fed7aa", borderWidth: 1, gap: 10, marginBottom: 12, padding: 12 },
  remoteContentText: { color: "#7c2d12", fontWeight: "800", lineHeight: 20 },
  readerCopy: { color: "#4b5f77", lineHeight: 24, marginTop: 12, maxWidth: 720 },
  settingsPane: { flex: 1, backgroundColor: "#f7f9fc" },
  settingsContent: { padding: 22, gap: 18 },
  settingsTitle: { color: "#172033", fontSize: 28, fontWeight: "800" },
  settingsCopy: { color: "#4b5f77", lineHeight: 23, maxWidth: 860 },
  settingsColumns: { flexDirection: "row", flexWrap: "wrap", gap: 18 },
  settingsCard: { backgroundColor: "#ffffff", borderColor: "#d5dde7", borderWidth: 1, flexBasis: 430, flexGrow: 1, padding: 18 },
  cardTitle: { color: "#172033", fontSize: 19, fontWeight: "800", marginBottom: 14 },
  firstRunScroll: { flex: 1, backgroundColor: "#eaf1f8" },
  firstRunShell: { flex: 1, backgroundColor: "#eaf1f8", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 32, padding: 28 },
  firstRunShellMobile: { alignItems: "stretch", flexDirection: "column", flexGrow: 1, gap: 18, justifyContent: "flex-start", padding: 16 },
  firstRunBrand: { maxWidth: 520 },
  firstRunBrandMobile: { width: "100%" },
  brandMark: { color: "#0b63ce", fontSize: 22, fontWeight: "900", marginBottom: 18 },
  brandTitle: { color: "#132238", fontSize: 42, fontWeight: "900", lineHeight: 48, marginBottom: 18 },
  brandTitleMobile: { fontSize: 30, lineHeight: 35, marginBottom: 12 },
  brandCopy: { color: "#40566f", fontSize: 17, lineHeight: 27 },
  brandCopyMobile: { fontSize: 15, lineHeight: 23 },
  setupFlow: { backgroundColor: "#ffffff", borderColor: "#cbd7e3", borderWidth: 1, maxWidth: 620, padding: 18, width: "100%", gap: 16 },
  stepper: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  stepPill: { backgroundColor: "#edf2f7", paddingHorizontal: 8, paddingVertical: 4 },
  stepPillActive: { backgroundColor: "#0b63ce" },
  stepText: { color: "#53677f", fontSize: 12, fontWeight: "800" },
  stepTextActive: { color: "#ffffff" },
  formBlock: { gap: 13 },
  flowTitle: { color: "#172033", fontSize: 21, fontWeight: "800" },
  flowCopy: { color: "#4b5f77", lineHeight: 22 },
  statusNeutral: { color: "#4b5f77", fontWeight: "700" },
  statusOk: { color: "#17693a", fontWeight: "800" },
  statusError: { color: "#9f1239", fontWeight: "800" },
  field: { gap: 6 },
  fieldLabel: { color: "#24364e", fontWeight: "800" },
  input: { backgroundColor: "#ffffff", borderColor: "#b7c5d4", borderWidth: 1, color: "#111827", fontSize: 16, paddingHorizontal: 11, paddingVertical: 10 },
  authOptions: { gap: 10 },
  authOption: { borderColor: "#cbd7e3", borderWidth: 1, padding: 9 },
  authOptionActive: { backgroundColor: "#e7f1ff", borderColor: "#7aa7e8" },
  authOptionText: { color: "#172033", fontWeight: "800" },
  authOptionTextActive: { color: "#0b4f9c" },
  authOptionHelp: { color: "#64748b", marginTop: 5 },
  authOptionHelpActive: { color: "#255f9f" },
  reviewRow: { borderTopColor: "#e2e8f0", borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", gap: 12, paddingVertical: 9 },
  reviewLabel: { color: "#64748b", fontWeight: "800" },
  reviewValue: { color: "#172033", flex: 1, textAlign: "right" },
  successText: { color: "#17693a", fontWeight: "800" },
  errorText: { backgroundColor: "#fff1f2", borderColor: "#fecdd3", borderWidth: 1, color: "#9f1239", padding: 10 },
  flowButtons: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  buttonDisabled: { cursor: "default", opacity: 0.55 } as unknown as ViewStyle,
  manageAccountRow: { borderTopColor: "#e2e8f0", borderTopWidth: 1, gap: 10, paddingVertical: 12 },
  accountSummary: { alignItems: "center", flexDirection: "row", gap: 10 },
  avatar: { alignItems: "center", backgroundColor: "#dbeafe", height: 38, justifyContent: "center", width: 38 },
  avatarText: { color: "#0b4f9c", fontWeight: "900" },
  accountSummaryText: { flex: 1 },
  accountName: { color: "#172033", fontWeight: "800" },
  accountMeta: { color: "#64748b", fontSize: 12, marginTop: 2 },
  statusPill: { backgroundColor: "#dcfce7", color: "#166534", fontSize: 12, fontWeight: "800", overflow: "hidden", paddingHorizontal: 7, paddingVertical: 3 },
})
