import { StyleSheet, type ViewStyle } from "react-native"
import { DEFAULT_FOLDER_PANE_WIDTH, DIVIDER_WIDTH, MAX_FOLDER_PANE_WIDTH, MIN_FOLDER_PANE_WIDTH, MIN_MESSAGE_PANE_WIDTH } from "./layoutConstants"
import { Theme } from "./theme"

const C = Theme.colors

export const styles = StyleSheet.create({
  clickable: { cursor: "pointer" } as unknown as ViewStyle,
  shell: { flex: 1, backgroundColor: C.shellBg },
  toolbar: { minHeight: 58, backgroundColor: C.toolbarBg, borderBottomColor: C.toolbarBorder, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 14 },
  toolbarMobile: { alignItems: "stretch", flexDirection: "column", gap: 6, minHeight: 0, paddingHorizontal: 10, paddingVertical: 8 },
  toolbarTitleRow: { alignItems: "center", flexDirection: "row", gap: 8, minWidth: 0 },
  toolbarTitle: { color: C.toolbarText, fontSize: 19, fontWeight: "900", letterSpacing: 0.2 },
  toolbarTitleMobile: { flex: 1, fontSize: 17, minWidth: 0 },
  toolbarActions: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  toolbarActionsScroller: { width: "100%" },
  toolbarActionsMobile: { flexDirection: "row", flexWrap: "nowrap", gap: 8, justifyContent: "flex-start", paddingRight: 10 },
  toolbarActionControl: { flexShrink: 0, gap: 4, paddingHorizontal: 8, paddingVertical: 5 },
  toolbarActionText: { alignSelf: "center", fontSize: 11, fontWeight: "700", includeFontPadding: false, lineHeight: 11, paddingTop: 1, textAlign: "center", textAlignVertical: "center" } as unknown as ViewStyle,
  toolbarIconControl: { flexShrink: 0, height: 30, paddingHorizontal: 0, paddingVertical: 0, width: 30 },
  notice: { backgroundColor: C.noticeBg, borderBottomColor: C.noticeBorder, borderBottomWidth: 1, color: C.noticeText, fontWeight: "800", paddingHorizontal: 14, paddingVertical: 8 },
  vaultUnlock: { alignItems: "center", backgroundColor: C.warningBg, borderBottomColor: C.warningBorder, borderBottomWidth: 1, flexDirection: "row", gap: 10, paddingHorizontal: 14, paddingVertical: 8 },
  vaultUnlockText: { color: C.warningText, fontWeight: "800" },
  vaultUnlockInput: { backgroundColor: C.inputBg, borderColor: C.warningBorder, borderWidth: 1, color: C.textStrong, minWidth: 220, paddingHorizontal: 10, paddingVertical: 8 },
  vaultUnlockError: { color: C.dangerText, fontWeight: "800" },
  workspace: { flex: 1, flexDirection: "row", minHeight: 0 },
  folderPaneFallback: { backgroundColor: C.surfaceInset, flexBasis: DEFAULT_FOLDER_PANE_WIDTH, flexGrow: 0, flexShrink: 0, maxWidth: MAX_FOLDER_PANE_WIDTH, minWidth: MIN_FOLDER_PANE_WIDTH, overflow: "hidden", width: DEFAULT_FOLDER_PANE_WIDTH },
  folderPaneScroll: { flex: 1, minWidth: 0 },
  folderDrawerBackdrop: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0, zIndex: 900 },
  folderDrawerScrim: { backgroundColor: C.scrim, bottom: 0, left: 0, position: "absolute", right: 0, top: 0 } as unknown as ViewStyle,
  folderDrawerPanel: { backgroundColor: C.surfaceInset, borderRightColor: C.borderStrong, borderRightWidth: 1, bottom: 0, left: 0, maxWidth: 360, position: "absolute", top: 0, width: "86%" } as unknown as ViewStyle,
  folderDrawerHeader: { alignItems: "center", borderBottomColor: C.divider, borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 12, paddingVertical: 10 },
  dragDivider: { backgroundColor: C.divider, flexShrink: 0, width: DIVIDER_WIDTH },
  folderPaneContent: { padding: 8, gap: 3 },
  paneHeader: { color: C.text, fontSize: 13, fontWeight: "800", marginBottom: 8, textTransform: "uppercase" },
  sectionHeader: { color: C.textMuted, fontSize: 12, fontWeight: "800", marginTop: 16, marginBottom: 6, textTransform: "uppercase" },
  folderButton: { alignItems: "center", flexDirection: "row", gap: 6, justifyContent: "space-between", paddingHorizontal: 6, paddingVertical: 5 },
  folderButtonActive: { backgroundColor: C.accentSoft, borderColor: C.accentBorder, borderLeftWidth: 3 },
  folderButtonDropTarget: { backgroundColor: C.dropBg, borderColor: C.dropBorder, borderWidth: 1 },
  folderLabelGroup: { flex: 1, minWidth: 0 },
  folderButtonText: { color: C.text, flex: 1, fontSize: 14, fontWeight: "600", minWidth: 0 },
  folderButtonTextActive: { color: C.accentActive },
  folderBadgeText: { color: C.textMuted, fontSize: 10, fontWeight: "800", marginTop: 2, textTransform: "uppercase" },
  folderCount: { color: C.textMuted, flexShrink: 0, fontWeight: "800" },
  accountTree: { marginTop: 8 },
  accountTreeHeader: { paddingHorizontal: 8, paddingVertical: 7 },
  accountTreeName: { color: C.textStrong, fontWeight: "800" },
  accountTreeServer: { color: C.textMuted, fontSize: 12, marginTop: 2 },
  accountTreeStatus: { color: C.textMuted, fontSize: 11, marginTop: 3 },
  accountTreeError: { color: C.dangerText, fontSize: 11, fontWeight: "800", marginTop: 3 },
  compactButton: { gap: 4, paddingHorizontal: 6, paddingVertical: 3 },
  compactButtonText: { fontSize: 10, fontWeight: "800" },
  squareIconButton: { height: 24, paddingHorizontal: 0, paddingVertical: 0, width: 24 },
  mailWorkspace: { flex: 1, flexDirection: "row", minWidth: 0 },
  mailWorkspaceMobile: { flex: 1, flexDirection: "column", minWidth: 0 },
  threadPaneFallback: { backgroundColor: C.surface, borderLeftColor: C.border, borderLeftWidth: 1, flexBasis: "50%", flexGrow: 0, flexShrink: 0, minWidth: MIN_MESSAGE_PANE_WIDTH, overflow: "hidden", width: "50%" },
  threadPaneMobile: { backgroundColor: C.surface, flex: 1, minWidth: 0 },
  threadHeader: { backgroundColor: C.surfaceAlt, borderBottomColor: C.border, borderBottomWidth: 1, padding: 14 },
  threadTitle: { color: C.textStrong, fontSize: 20, fontWeight: "800" },
  threadSubtle: { color: C.textMuted, marginTop: 5 },
  statusInline: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 5 },
  searchRow: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 12 },
  searchRowMobile: { alignItems: "stretch", flexWrap: "wrap" },
  searchInput: { backgroundColor: C.inputBg, borderColor: C.borderStrong, borderWidth: 1, color: C.textStrong, flex: 1, fontSize: 14, minWidth: 0, paddingHorizontal: 10, paddingVertical: 8 },
  messageListShell: { flex: 1, minHeight: 0, position: "relative" },
  messageList: { flex: 1, backgroundColor: C.surface },
  messageRow: { borderBottomColor: C.borderSoft, borderBottomWidth: 1, gap: 4, paddingHorizontal: 12, paddingVertical: 10 },
  messageRowFlagged: { backgroundColor: C.flaggedBg },
  messageRowDone: { backgroundColor: C.doneBg },
  messageRowActive: { backgroundColor: C.accentSoft, borderLeftColor: C.accent, borderLeftWidth: 3 },
  messageRowFlaggedActive: { backgroundColor: C.flaggedBgActive },
  messageRowDoneActive: { backgroundColor: C.doneBgActive },
  messageRowTop: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" },
  messageSenderGroup: { alignItems: "center", flex: 1, flexDirection: "row", gap: 7, minWidth: 0 },
  unreadMarker: { backgroundColor: C.accent, height: 7, width: 7 },
  messageSender: { color: C.textStrong, flex: 1, fontWeight: "800", minWidth: 0 },
  messageSenderRead: { color: C.text, fontWeight: "600" },
  messageRowActions: { alignItems: "center", flexDirection: "row", flexShrink: 0, gap: 6 },
  messageDate: { color: C.textMuted, flexShrink: 0, fontSize: 11 },
  flagButton: { alignItems: "center", height: 24, justifyContent: "center", width: 24 },
  messageSubject: { color: C.text, fontWeight: "800" },
  messageSubjectRead: { color: C.textSoft, fontWeight: "600" },
  messageMetaText: { color: C.textMuted, fontSize: 12 },
  messagePreviewText: { color: C.textMuted, lineHeight: 18 },
  attachmentText: { color: C.accentActive, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  attachmentList: { backgroundColor: C.surfaceAlt, borderColor: C.border, borderWidth: 1, gap: 8, marginTop: 10, padding: 8 },
  attachmentListHeader: { alignItems: "center", flexDirection: "row", gap: 8, justifyContent: "space-between" },
  attachmentListTitle: { color: C.text, fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  attachmentGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  attachmentItem: { alignItems: "center", backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, flexBasis: 210, flexDirection: "row", flexGrow: 1, gap: 8, justifyContent: "space-between", minWidth: 0, paddingHorizontal: 7, paddingVertical: 5 },
  attachmentFileText: { flex: 1, minWidth: 0 },
  attachmentName: { color: C.textStrong, fontSize: 13, fontWeight: "800" },
  attachmentMeta: { color: C.textMuted, fontSize: 11, marginTop: 2 },
  attachmentActions: { alignItems: "center", flexDirection: "row", flexShrink: 0, gap: 5 },
  attachmentLoadingText: { color: C.textMuted, fontSize: 11, fontWeight: "800" },
  contextMenuLayer: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0, zIndex: 1200 },
  contextMenuLayerWeb: { position: "fixed" } as unknown as ViewStyle,
  contextMenuBackdrop: { bottom: 0, left: 0, position: "absolute", right: 0, top: 0 } as unknown as ViewStyle,
  contextMenu: { backgroundColor: C.surface, borderColor: C.borderStrong, borderWidth: 1, minWidth: 210, paddingVertical: 4, position: "absolute", shadowColor: C.shadow, shadowOpacity: 0.18, shadowRadius: 12, zIndex: 1201 } as unknown as ViewStyle,
  contextMenuItem: { alignItems: "center", flexDirection: "row", gap: 9, justifyContent: "flex-start", paddingHorizontal: 12, paddingVertical: 9 },
  contextMenuText: { color: C.textStrong, fontSize: 13, fontWeight: "800" },
  contextMenuTextDestructive: { color: C.dangerText },
  loadMoreArea: { alignItems: "center", borderTopColor: C.borderSoft, borderTopWidth: 1, paddingHorizontal: 12, paddingVertical: 14 },
  emptyThreads: { padding: 22 },
  emptyTitle: { color: C.textStrong, fontSize: 18, fontWeight: "800" },
  emptyCopy: { color: C.textMuted, lineHeight: 22, marginTop: 8 },
  readerPane: { backgroundColor: C.readerBg, flex: 1, minWidth: MIN_MESSAGE_PANE_WIDTH, padding: 28 },
  readerPaneMobile: { minWidth: 0, overflow: "hidden", padding: 14 },
  readerContent: { paddingBottom: 40 },
  readerTitleRow: { alignItems: "flex-start", flexDirection: "row", gap: 10, justifyContent: "space-between" },
  readerTitleRowMobile: { flexWrap: "nowrap" },
  readerTitle: { color: C.textStrong, flex: 1, fontSize: 24, fontWeight: "800", minWidth: 0 },
  readerTitleMobile: { flexBasis: 0, overflowWrap: "anywhere", wordBreak: "break-word" } as unknown as ViewStyle,
  readerMeta: { color: C.textMuted, marginTop: 8 },
  readerActionRow: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
  readerActionButton: { paddingHorizontal: 8, paddingVertical: 5 },
  readerBody: { color: C.textStrong, fontSize: 15, lineHeight: 23, marginTop: 24, maxWidth: "100%", overflowX: "auto", whiteSpace: "pre-wrap" } as unknown as ViewStyle,
  readerLoading: { alignItems: "flex-start", marginTop: 24 },
  htmlPreviewBlock: { marginTop: 24, maxWidth: "100%", overflowX: "auto", overflowY: "visible" } as unknown as ViewStyle,
  inlineContentNotice: { backgroundColor: C.noticeBg, borderColor: C.noticeBorder, borderWidth: 1, gap: 10, marginBottom: 12, padding: 12 },
  inlineContentText: { color: C.noticeText, fontWeight: "800", lineHeight: 20 },
  remoteContentNotice: { backgroundColor: C.warningBg, borderColor: C.warningBorder, borderWidth: 1, gap: 10, marginBottom: 12, padding: 12 },
  remoteContentText: { color: C.warningText, fontWeight: "800", lineHeight: 20 },
  readerCopy: { color: C.textSoft, lineHeight: 24, marginTop: 12, maxWidth: 720 },
  composePane: { backgroundColor: C.readerBg, flex: 1, minWidth: MIN_MESSAGE_PANE_WIDTH },
  composePaneMobile: { minWidth: 0, overflow: "hidden" },
  composeContent: { gap: 16, padding: 22, paddingBottom: 40 },
  composeHeader: { alignItems: "flex-start", backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, flexDirection: "row", gap: 12, justifyContent: "space-between", padding: 14 },
  composeTitleGroup: { flex: 1, minWidth: 0 },
  composeKicker: { color: C.accent, fontSize: 11, fontWeight: "900", letterSpacing: 0.8, textTransform: "uppercase" },
  composeTitle: { color: C.textStrong, fontSize: 24, fontWeight: "900", marginTop: 2 },
  composeMeta: { color: C.textMuted, fontSize: 12, fontWeight: "700", marginTop: 6 },
  composeAccountList: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  composeAccountButton: { paddingHorizontal: 7, paddingVertical: 4 },
  composeFields: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, gap: 10, padding: 14 },
  composeField: { gap: 6 },
  composeInput: { fontSize: 14, paddingVertical: 8 },
  composeBodyInput: { fontSize: 15, lineHeight: 22, minHeight: 280 },
  composeActions: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "flex-end" },
  settingsPane: { flex: 1, backgroundColor: C.readerBg },
  settingsContent: { padding: 22, gap: 18 },
  settingsTitle: { color: C.textStrong, fontSize: 28, fontWeight: "800" },
  settingsCopy: { color: C.textSoft, lineHeight: 23, maxWidth: 860 },
  settingsColumns: { flexDirection: "row", flexWrap: "wrap", gap: 18 },
  settingsCard: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, flexBasis: 430, flexGrow: 1, padding: 18 },
  cardTitle: { color: C.textStrong, fontSize: 19, fontWeight: "800", marginBottom: 14 },
  themeModeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  themeModeButton: { minWidth: 82, justifyContent: "center" },
  firstRunScroll: { flex: 1, backgroundColor: C.setupBg },
  firstRunShell: { flex: 1, backgroundColor: C.setupBg, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 32, padding: 28 },
  firstRunShellMobile: { alignItems: "stretch", flexDirection: "column", flexGrow: 1, gap: 18, justifyContent: "flex-start", padding: 16 },
  setupFlow: { backgroundColor: C.surface, borderColor: C.border, borderWidth: 1, maxWidth: 620, padding: 18, width: "100%", gap: 16 },
  stepper: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  stepPill: { backgroundColor: C.surfaceInset, paddingHorizontal: 8, paddingVertical: 4 },
  stepPillActive: { backgroundColor: C.accent },
  stepText: { color: C.textMuted, fontSize: 12, fontWeight: "800" },
  stepTextActive: { color: C.accentContrast },
  formBlock: { gap: 13 },
  flowTitle: { color: C.textStrong, fontSize: 21, fontWeight: "800" },
  flowCopy: { color: C.textSoft, lineHeight: 22 },
  statusNeutral: { color: C.textSoft, fontWeight: "700" },
  statusOk: { color: C.statusOkText, fontWeight: "800" },
  statusError: { color: C.dangerText, fontWeight: "800" },
  field: { gap: 6 },
  fieldLabel: { color: C.text, fontWeight: "800" },
  input: { backgroundColor: C.inputBg, borderColor: C.borderStrong, borderWidth: 1, color: C.textStrong, fontSize: 16, paddingHorizontal: 11, paddingVertical: 10 },
  authOptions: { gap: 10 },
  authOption: { alignItems: "stretch", borderColor: C.border, borderWidth: 1, flexDirection: "column", justifyContent: "flex-start", padding: 9 },
  authOptionActive: { backgroundColor: C.accentSoft, borderColor: C.accentBorder },
  authOptionText: { color: C.textStrong, fontWeight: "800" },
  authOptionTextActive: { color: C.accentActive },
  authOptionHelp: { color: C.textMuted, marginTop: 5 },
  authOptionHelpActive: { color: C.authActiveText },
  reviewRow: { borderTopColor: C.borderSoft, borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", gap: 12, paddingVertical: 9 },
  reviewLabel: { color: C.textMuted, fontWeight: "800" },
  reviewValue: { color: C.textStrong, flex: 1, textAlign: "right" },
  successText: { color: C.statusOkText, fontWeight: "800" },
  errorText: { backgroundColor: C.dangerBg, borderColor: C.dangerBorder, borderWidth: 1, color: C.dangerText, padding: 10 },
  flowButtons: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  manageAccountRow: { borderTopColor: C.borderSoft, borderTopWidth: 1, gap: 10, paddingVertical: 12 },
  accountSummary: { alignItems: "center", flexDirection: "row", gap: 10 },
  avatar: { alignItems: "center", backgroundColor: C.avatarBg, height: 38, justifyContent: "center", width: 38 },
  avatarText: { color: C.accentActive, fontWeight: "900" },
  accountSummaryText: { flex: 1 },
  accountName: { color: C.textStrong, fontWeight: "800" },
  accountMeta: { color: C.textMuted, fontSize: 12, marginTop: 2 },
  statusPill: { backgroundColor: C.statusOkBg, color: C.statusOkText, fontSize: 12, fontWeight: "800", overflow: "hidden", paddingHorizontal: 7, paddingVertical: 3 },
})
